# coding: utf-8

"""
    SensCritique Mobile API

    Unofficial SensCritique API

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class PaginatedProductListResponsePaging(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, after=None, before=None):
        """
        PaginatedProductListResponsePaging - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'after': 'str',
            'before': 'str'
        }

        self.attribute_map = {
            'after': 'after',
            'before': 'before'
        }

        self._after = after
        self._before = before

    @property
    def after(self):
        """
        Gets the after of this PaginatedProductListResponsePaging.
        Url to the next page

        :return: The after of this PaginatedProductListResponsePaging.
        :rtype: str
        """
        return self._after

    @after.setter
    def after(self, after):
        """
        Sets the after of this PaginatedProductListResponsePaging.
        Url to the next page

        :param after: The after of this PaginatedProductListResponsePaging.
        :type: str
        """

        self._after = after

    @property
    def before(self):
        """
        Gets the before of this PaginatedProductListResponsePaging.
        Url to the previous page

        :return: The before of this PaginatedProductListResponsePaging.
        :rtype: str
        """
        return self._before

    @before.setter
    def before(self, before):
        """
        Sets the before of this PaginatedProductListResponsePaging.
        Url to the previous page

        :param before: The before of this PaginatedProductListResponsePaging.
        :type: str
        """

        self._before = before

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
